---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acmhub
  namespace: open-cluster-management-global-set
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-acmhub
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: acmhub-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: open-cluster-management-global-set
      source:
        repoURL: https://github.com/eformat/acm-gitops-policies.git
        path: policies/base/CM-Configuration-Management/advanced-cluster-management
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
