---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-argo
  namespace: open-cluster-management-global-set
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-all-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: team-argo-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: open-cluster-management-global-set
      source:
        repoURL: https://github.com/eformat/acm-gitops.git
        path: team-gitops-policy
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
