---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-certificate-expiration
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-8 Transmission Confidentiality and Integrity
    policy.open-cluster-management.io/standards: NIST 800-53
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy # cert management expiration
        metadata:
          name: policy-certificate-expiration-minimum
        spec:
          minimumDuration: 600h
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - openshift-ingress
              - openshift-config
          remediationAction: inform
          severity: low
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-certificate-expiration
placementRef:
  apiGroup: apps.open-cluster-management.io
  name: all-clusters
  kind: PlacementRule
subjects:
  - name: baseline-cluster-config
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet
