---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: acmhub
placementBindingDefaults:
  name: acmhub
policyDefaults:
  placement:
    placementName: placement-acmhub
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  controls: 
    - CM-2 Baseline Configuration
  consolidateManifests: false
  disabled: false
  namespace: open-cluster-management-global-set
  pruneObjectBehavior: "DeleteAll"
  remediationAction: enforce
  severity: medium
  standards:
    - generic
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous"}
policies:
  - name: acmhub
    manifests:
      - path: generator-input/
