namespace: open-cluster-management-global-set

bases:
- ../../base

resources:
  - policy-config-gpu-iommu.yml
  - policy-config-nfd-operator-instance.yml
  - policy-config-nvidia-gpu-operator-clusterpolicy.yml
  - policyset-nvidia-gpu-policies.yml
